# @package _global_

defaults:
  - data: metaworld
  - policy: skill_gpt
  - train: default
  - eval: default
  - _self_

# change defaults
data:
  seq_len: 32
  obs_seq_len: 1

tune_decoder: false

pretrain_model_path: "/PRIMO/experiments_finetune/metaworld/ML5/SkillGPT_Model/qst_32_f4_d256_k3s4_n6d384_5shot/run_001/multitask_model_ep400.pth"

exp_name: "qst_32_f4_d256_k3s4_n6d384_5shot" # 
seed: 1

use_wandb: false
wandb_project: "skill-metaworld"

device: "cuda"

benchmark_name: "metaworld"
sub_benchmark_name: "ML5"

video_dir: '/PRIMO/mpc2_ep10_videos'
save_video: false