# @package _global_

defaults:
  - data: metaworld
  - policy: bc_transformer_policy
  - train: default
  - eval: default
  - _self_

# change defaults
data:
  seq_len: 10
  obs_seq_len: 10

tune_decoder: false

pretrain_model_path: "/PRIMO/experiments_finetune/metaworld/ML5/BCTransformerPolicy/bc_resnetT_5shot/run_001/multitask_model_ep400.pth"

exp_name: "bc_resnetT_5shot" # 
seed: 1

use_wandb: false
wandb_project: "skill-metaworld"

device: "cuda"

benchmark_name: "metaworld"
sub_benchmark_name: "ML5"

video_dir: '/PRIMO/mpc2_ep10_videos'
save_video: false