# @package _global_

defaults:
  - data: metaworld
  - policy: diffusion_policy
  - train: default
  - eval: default
  - _self_

# change defaults
data:
  seq_len: 16
  obs_seq_len: 1

tune_decoder: false

pretrain_model_path: "/PRIMO/experiments_finetune/metaworld/ML5/Diffusion_Policy/diff_16_l3d256_5shot/run_001/multitask_model_ep400.pth"

exp_name: "diff_16_l3d256_5shot" # 
seed: 1

use_wandb: false
wandb_project: "skill-metaworld"

device: "cuda"

benchmark_name: "metaworld"
sub_benchmark_name: "ML5"

video_dir: '/PRIMO/diffusion_videos'
save_video: false