# @package _global_

defaults:
  - data: metaworld
  - policy: vq_bet
  - train: default
  - eval: default
  - _self_

# change defaults
data:
  seq_len: 14
  obs_seq_len: 10

tune_decoder: false

pretrain_model_path: "/PRIMO/experiments_finetune/metaworld/ML5/VQBet_Model/bet_5_2c32_n6d120_5shot/run_001/multitask_model_ep400.pth"

exp_name: "bet_5_2c32_n6d120_5shot" # 
seed: 1

use_wandb: false
wandb_project: "skill-metaworld"

device: "cuda"

benchmark_name: "metaworld"
sub_benchmark_name: "ML5"

video_dir: '/PRIMO/diffusion_videos'
save_video: false