# observation related
seq_len: 32
obs_seq_len: 1
frame_stack: 1

# TODO: this assumes that all images have the same shape and there is one proprio input which makes
# things much cleaner
shape_meta:
  action_dim: 4
  proprio_dim: 8
  image_shape: [3, 128, 128]
  image_inputs:
    - corner_rgb


obs_modality:
  rgb: ["corner_rgb"]
  depth: []
  low_dim: ["robot_states"]

benchmark_name: metaworld
sub_benchmark_name: ML45
data_dir: metaworld
# todo: not sure exactly how to handle this for train / eval split. will deal with later
n_tasks: 45