# observation related
seq_len: ${algo.skill_block_size}
obs_seq_len: 1
frame_stack: 1

benchmark_name: metaworld
sub_benchmark_name: ML45
mode: train
# todo: not sure exactly how to handle this for train / eval split. will deal with later
n_tasks: 45

# TODO: this assumes that all images have the same shape and there is one proprio input which makes
# things much cleaner
img_height: 128
img_width: 128
shape_meta:
  action_dim: 4
  proprio_dim: 8
  image_shape: 
    - 3
    - ${task.img_height}
    - ${task.img_width}
  image_inputs:
    - corner_rgb

# build_dataset(data_prefix, benchmark_name, sub_benchmark_name, seq_len, obs_seq_len, obs_modality):
dataset:
  _target_: quest.utils.metaworld_utils.build_dataset
  data_prefix: ${data_prefix}
  benchmark_name: ${task.benchmark_name}
  sub_benchmark_name: ${task.sub_benchmark_name}
  mode: ${task.mode}
  seq_len: ${task.seq_len}
  obs_seq_len: ${task.obs_seq_len}
  obs_modality:
    rgb: ["corner_rgb"]
    depth: []
    low_dim: ["robot_states"]
  load_obs: ${training.load_obs}

env_runner:
  _target_: quest.env_runner.metaworld_runner.MetaWorldRunner
  env_factory:
    _target_: quest.utils.metaworld_utils.MetaWorldWrapper
    _partial_: true 
    img_height: ${task.img_height}
    img_width: ${task.img_width}
    max_episode_length: ${rollout.max_episode_length}
    camera_name: 'corner2'
    env_kwargs: null
  benchmark:
    _target_: metaworld.ML45
  mode: ${task.mode}
  rollouts_per_env: ${rollout.rollouts_per_env}
  fps: 24
  
