# @package _global_

defaults:
  - data: metaworld
  - policy: skill_gpt
  - train: default
  - eval: default
  - _self_

# change defaults
data:
  seq_len: 32
  obs_seq_len: 1

tune_decoder: false

pretrain_model_path: "/satassdscratch/amete7/PRIMO/experiments/metaworld/ML45/SkillGPT_Model/v1td_32_f4_k3s4_tt_n6d384/run_001/multitask_model_ep50.pth"

exp_name: "v1td_32_f4_k3s4_tt_n6d384" # 
seed: 1

use_wandb: false
wandb_project: "skill-metaworld"

device: "cuda"

benchmark_name: "metaworld"
sub_benchmark_name: "ML45"
