# @package _global_

defaults:
  - data: metaworld
  - policy: vq_bet
  - train: default
  - _self_

# change defaults
data:
  seq_len: 14
  obs_seq_len: 10
  few_shot_demos: [1, 5, 10, 20, 45]
train:
  batch_size: 128
  num_workers: 4
  n_epochs: 100
  save_interval: 10
tune_decoder: true # remove .detach() from vqbet!!!!!!!

pretrain_model_path: ""

exp_name: bet_5_2c32_n6d120 # 'diff_16_l3d256'  # "qst_32_f4_d256_k3s4_n6d384" # 
seed: 10000

use_wandb: true
wandb_project: "skill-metaworld"

device: "cuda"

benchmark_name: "metaworld"
sub_benchmark_name: "ML45"
