# @package _global_

defaults:
  - data: metaworld
  - policy: skill_vae
  - train: default
  - _self_

# change defaults
data:
  seq_len: 8
  obs_seq_len: 1
train:
  batch_size: 256
  num_workers: 4
  n_epochs: 500
policy:
  skill_block_size: 8
  fsq_level: [8,5,5,5]
  kernel_sizes: [5,3,3]
  strides: [2,1,1]

exp_name: "v1td_8_f4_k3s2_tt" # 
seed: 10000

use_wandb: true
wandb_project: "skill-metaworld"

device: "cuda"

benchmark_name: "metaworld"
sub_benchmark_name: "ML45"
