# @package _global_

defaults:
  - data: metaworld
  - policy: vq_vae
  - train: default
  - _self_

# change defaults
data:
  seq_len: 5
  obs_seq_len: 1
train:
  batch_size: 256
  num_workers: 4
  n_epochs: 500

exp_name: "bet_5_2c32" # 
seed: 10000

use_wandb: true
wandb_project: "skill-metaworld"

device: "cuda"

benchmark_name: "metaworld"
sub_benchmark_name: "ML45"
