# @package _global_

defaults:
  - data: metaworld
  - policy: bc_transformer_policy
  - train: default
  - _self_

# change defaults
data:
  seq_len: 10
  obs_seq_len: 10
train:
  batch_size: 128
  num_workers: 4
  n_epochs: 100
  save_interval: 10
tune_decoder: false

pretrain_model_path: ""

exp_name: 'bc_resnetT' #bet_5_2c32_n6d120 # 'diff_16_l3d256'  # "qst_32_f4_d256_k3s4_n6d384" # 
seed: 10000

use_wandb: false
wandb_project: "skill-metaworld"

device: "cuda"

benchmark_name: "metaworld"
sub_benchmark_name: "ML45"
