defaults:
  - train_base
  - _self_

stage: 2 # 0 - pretrain autoencoder, 1 - train multitask, 2 - finetune multitask

# training:
#   save_interval: 10

training:
  n_epochs: 200
  save_interval: 10

rollout:
  interval: 25
  rollouts_per_env: 5


logging_folder: fewshot