defaults:
  - task: metaworld_ml45
  - algo: ppo
  - _self_

training:
  # training
  n_epochs: 2000
  grad_clip: 100.
  save_interval: 100
  log_interval: 100
  use_amp: false
  use_tqdm: true
  do_profile: False
  save_all_checkpoints: false
  auto_continue: false # if true, it will automatically continue from the end of stage n training for stage n+1 training
  load_obs: true

  # resume training
  resume: false
  resume_path: ""

# todo: add some rudimentary online eval rollouts

rollout:
  enabled: true
  interval: 10
  rollouts_per_env: 1
  max_episode_length: 200


logging:
  group: null
  mode: online # set logging.mode=disabled to disable wandb
  project: skill-metaworld
  resume: true
  save_code: true

task_id: 2 # task id for the most similar task from pretraining tasks
env:
  num_envs: 32
  env_name: door-lock-v2
  mode: ${task.mode}
  img_height: 128
  img_width: 128
  max_episode_length: 512

num_steps: ${eval:'${env.max_episode_length} // ${algo.action_horizon}'}

exp_name: door_lock_tr2 # 
variant_name: null
seed: 10000
device: cuda:0
stage: 1 # 0 - pretrain autoencoder, 1 - train multitask, 2 - finetune multitask
output_prefix: ./experiments
data_prefix: ./data
make_unique_experiment_dir: true

checkpoint_path: null
pretrained_path: '/satassdscratch/amete7/PRIMO/debug_model.pth'
