defaults:
  - task: metaworld_ml45
  - algo: ppo
  - _self_

training:
  # training
  n_epochs: 2000
  save_interval: 100
  log_interval: 100
  use_amp: false
  use_tqdm: true
  do_profile: False
  save_all_checkpoints: true
  auto_continue: false # if true, it will automatically continue from the end of stage n training for stage n+1 training
  load_obs: true

  # resume training
  resume: false
  resume_path: ""

# todo: add some rudimentary online eval rollouts

rollout:
  enabled: true
  interval: 10
  rollouts_per_env: 1
  max_episode_length: 200


logging:
  group: null
  mode: online # set logging.mode=disabled to disable wandb
  project: skill-metaworld
  resume: true
  save_code: true

env:
  num_envs: 32
  env_name: box-close-v2
  mode: test
  img_height: 128
  img_width: 128
  max_episode_length: 512

debug: false
save_video: false
override_task: hammer-v2
num_steps: ${eval:'${env.max_episode_length} // ${algo.action_horizon}'}

exp_name: over_default
variant_name: ${env.env_name}
seed: 0
device: cuda:0
output_prefix: ./experiments
data_prefix: ./data
make_unique_experiment_dir: true

checkpoint_path: null
pretrained_path: './debug_model_2.pth'
