defaults:
  - train_base
  - _self_

# Override frame stack to be zero so we don't load a bunch of past observations we don't need
algo:
  frame_stack: 1

train_dataloader:
  batch_size: 256


training:
  n_epochs: 500
  use_amp: false # this seems to cause instabilities for shorter chunks (<64) but causes speedups for larger ones

rollout:
  enabled: false
  rollouts_per_env: null
  max_episode_length: null

stage: 0 # 0 - pretrain autoencoder, 1 - train multitask, 2 - finetune multitask



